//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect.Model.LocalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalAsignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocalAsignment()
        {
            this.Inspection = new HashSet<LocalInspection>();
        }
    
        public int client_id { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public System.DateTime deadline { get; set; }
        public string state { get; set; }
        public string clarification { get; set; }
    
        public virtual LocalClient Client { get; set; }
        public virtual LocalState State1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalInspection> Inspection { get; set; }
    }
}
