//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect.Model.LocalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formfield
    {
        public int form_id { get; set; }
        public string field_title { get; set; }
        public int field_template_id { get; set; }
        public string value { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Form Form { get; set; }
    }
}
