//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect.Model.LocalModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDatabaseEntities : DbContext
    {
        public LocalDatabaseEntities()
            : base("name=LocalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LocalAbsence> Absence { get; set; }
        public virtual DbSet<LocalAsignment> Asignment { get; set; }
        public virtual DbSet<LocalClient> Client { get; set; }
        public virtual DbSet<LocalContactperson> Contactperson { get; set; }
        public virtual DbSet<LocalDatatype> Datatype { get; set; }
        public virtual DbSet<LocalEmployee> Employee { get; set; }
        public virtual DbSet<LocalEmployee_Status> Employee_Status { get; set; }
        public virtual DbSet<LocalField> Field { get; set; }
        public virtual DbSet<LocalForm> Form { get; set; }
        public virtual DbSet<LocalFormfield> Formfield { get; set; }
        public virtual DbSet<LocalImage> Image { get; set; }
        public virtual DbSet<LocalInspection> Inspection { get; set; }
        public virtual DbSet<LocalParkinglot> Parkinglot { get; set; }
        public virtual DbSet<LocalRegion> Region { get; set; }
        public virtual DbSet<LocalReport> Report { get; set; }
        public virtual DbSet<LocalReportFieldType> ReportFieldType { get; set; }
        public virtual DbSet<LocalRole> Role { get; set; }
        public virtual DbSet<LocalState> State { get; set; }
        public virtual DbSet<LocalTemplate> Template { get; set; }
    }
}
