//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect.Model.LocalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalReport
    {
        public int inspection_id { get; set; }
        public string clarifaction { get; set; }
        public string pdf { get; set; }
    
        public virtual LocalInspection Inspection { get; set; }
    }
}
