//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public System.DateTime start_date { get; set; }
        public int employee_id { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
