//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afbeelding
    {
        public string afbeelding1 { get; set; }
        public int rapportage_inspectie_id { get; set; }
    
        public virtual Rapportage Rapportage { get; set; }
    }
}
