//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afwezigheid
    {
        public System.DateTime start { get; set; }
        public int werknemer_id { get; set; }
        public Nullable<System.DateTime> einde { get; set; }
    
        public virtual Werknemer Werknemer { get; set; }
    }
}
