//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactpersoon
    {
        public int id { get; set; }
        public int klant_id { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
    
        public virtual Klant Klant { get; set; }
    }
}
