//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.Inspection1 = new HashSet<Inspection>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int id { get; set; }
        public int parkeerplaats_id { get; set; }
        public Nullable<int> vragenlijst_id { get; set; }
        public Nullable<int> vervolg_inspectie_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string toelichting { get; set; }
        public int opdracht_klant_id { get; set; }
        public int opdracht_id { get; set; }
    
        public virtual Asignment Asignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection> Inspection1 { get; set; }
        public virtual Inspection Inspection2 { get; set; }
        public virtual Parkinglot Parkinglot { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Questionair Questionair { get; set; }
        public virtual Raport Raport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
