//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspectie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspectie()
        {
            this.Inspectie1 = new HashSet<Inspectie>();
            this.Werknemer = new HashSet<Werknemer>();
        }
    
        public int id { get; set; }
        public int parkeerplaats_id { get; set; }
        public Nullable<int> vragenlijst_id { get; set; }
        public Nullable<int> vervolg_inspectie_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public string toelichting { get; set; }
        public int opdracht_klant_id { get; set; }
        public int opdracht_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie> Inspectie1 { get; set; }
        public virtual Inspectie Inspectie2 { get; set; }
        public virtual Opdracht Opdracht { get; set; }
        public virtual Parkeerplaats Parkeerplaats { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Vragenlijst Vragenlijst { get; set; }
        public virtual Rapportage Rapportage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Werknemer> Werknemer { get; set; }
    }
}
