//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opdracht
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opdracht()
        {
            this.Inspectie = new HashSet<Inspectie>();
        }
    
        public int klant_id { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> datum { get; set; }
        public System.DateTime deadine { get; set; }
        public string status { get; set; }
        public string toelichting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie> Inspectie { get; set; }
        public virtual Klant Klant { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
