//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkInspectModels : DbContext
    {
        public ParkInspectModels()
            : base("name=ParkInspectModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Afbeelding> Afbeelding { get; set; }
        public virtual DbSet<Afwezigheid> Afwezigheid { get; set; }
        public virtual DbSet<Contactpersoon> Contactpersoon { get; set; }
        public virtual DbSet<Datatype> Datatype { get; set; }
        public virtual DbSet<Inspectie> Inspectie { get; set; }
        public virtual DbSet<Klant> Klant { get; set; }
        public virtual DbSet<Opdracht> Opdracht { get; set; }
        public virtual DbSet<Parkeerplaats> Parkeerplaats { get; set; }
        public virtual DbSet<Rapportage> Rapportage { get; set; }
        public virtual DbSet<RapportVeldType> RapportVeldType { get; set; }
        public virtual DbSet<Regio> Regio { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<Veld> Veld { get; set; }
        public virtual DbSet<Vragenlijst> Vragenlijst { get; set; }
        public virtual DbSet<Vragenlijstveld> Vragenlijstveld { get; set; }
        public virtual DbSet<Werknemer> Werknemer { get; set; }
        public virtual DbSet<Werknemer_Status> Werknemer_Status { get; set; }
    }
}
