//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkInspectEntities : DbContext
    {
        public ParkInspectEntities()
            : base("name=ParkInspectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absence { get; set; }
        public virtual DbSet<Asignment> Asignment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contactman> Contactman { get; set; }
        public virtual DbSet<Datatype> Datatype { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_Status> Employee_Status { get; set; }
        public virtual DbSet<Field> Field { get; set; }
        public virtual DbSet<Form> Form { get; set; }
        public virtual DbSet<Formfield> Formfield { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<Parkinglot> Parkinglot { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReportFieldType> ReportFieldType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Template> Template { get; set; }
    }
}
