//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseTestEntities : DbContext
    {
        public DatabaseTestEntities()
            : base("name=DatabaseTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absence> Absence { get; set; }
        public virtual DbSet<Asignment> Asignment { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contactman> Contactman { get; set; }
        public virtual DbSet<Datatype> Datatype { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Employee_Status> Employee_Status { get; set; }
        public virtual DbSet<Field> Field { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Inspection> Inspection { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Parkinglot> Parkinglot { get; set; }
        public virtual DbSet<Questionair> Questionair { get; set; }
        public virtual DbSet<QuestionairField> QuestionairField { get; set; }
        public virtual DbSet<Raport> Raport { get; set; }
        public virtual DbSet<RaportFieldType> RaportFieldType { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Template> Template { get; set; }
    }
}
