//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veld
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veld()
        {
            this.Vragenlijstveld = new HashSet<Vragenlijstveld>();
        }
    
        public string titel { get; set; }
        public int template_id { get; set; }
        public string datatype { get; set; }
        public string rapportVeldType_titel { get; set; }
    
        public virtual Datatype Datatype1 { get; set; }
        public virtual RapportVeldType RapportVeldType { get; set; }
        public virtual Template Template { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vragenlijstveld> Vragenlijstveld { get; set; }
    }
}
