//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vragenlijstveld
    {
        public int vragenlijst_id { get; set; }
        public string veld_titel { get; set; }
        public int veld_template_id { get; set; }
        public string waarde { get; set; }
    
        public virtual Veld Veld { get; set; }
        public virtual Vragenlijst Vragenlijst { get; set; }
    }
}
