//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkInspect
{
    using System;
    using System.Collections.Generic;
    
    public partial class Werknemer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Werknemer()
        {
            this.Afwezigheid = new HashSet<Afwezigheid>();
            this.Inspectie = new HashSet<Inspectie>();
        }
    
        public int id { get; set; }
        public string werknemer_status { get; set; }
        public string rol { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public bool actief { get; set; }
        public string telefoonnummer { get; set; }
        public System.DateTime in_dienst_datum { get; set; }
        public Nullable<System.DateTime> uit_dienst_datum { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Afwezigheid> Afwezigheid { get; set; }
        public virtual Rol Rol1 { get; set; }
        public virtual Werknemer_Status Werknemer_Status1 { get; set; }
        public virtual Regio Regio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspectie> Inspectie { get; set; }
    }
}
